---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hextris-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: hextris-dep
    spec:
      containers:
      - image: pylagg/first_repo:version1
        imagePullPolicy: Always
        name: hextris
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: "service-hextris"
spec:
  selector:
    app: hextris-dep
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
